api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    collection:
        pagination:
            enabled: false
#            maximum_items_per_page: 10
#            items_per_page: 10
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
